added severities to logger (close #36)
Cavonstavant/arcAAAAAAAAAAAAAAAAade pull request #37
Opened 2022-03-23 13:12 UTC by aurelenc

2022-03-23 13:20 UTC, Cavonstavant requested changes

2022-03-23 13:20 UTC, Cavonstavant commented on Src/Core/Logger.cpp
> +    switch (severity) {
do an array

2022-03-23 13:20 UTC, Cavonstavant commented on Src/Core/Logger.cpp
> +    switch (severity) {
Same

2022-03-23 13:20 UTC, Cavonstavant commented on Src/Core/Logger.hpp
> +        enum Severity {
Explicit enum values not needed
Add enum size type

2022-03-23 13:51 UTC, pariciadra approved these changes

2022-03-24 18:56 UTC, aurelenc commented on Src/Core/Logger.cpp
> +    switch (severity) {
no because it uses an enum

2022-03-24 18:56 UTC, aurelenc commented on Src/Core/Logger.cpp
> +    switch (severity) {
Same

2022-03-25 08:27 UTC, Cavonstavant approved these changes

2022-03-25 08:27 UTC, merged